# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [3]:
# Write your answer here
import numpy as np
# zeros = np.array([0,0,0,0,0,0,0,0,0,0])
zeros = np.zeros(10, dtype = int)
zeros
# zeros.dtype

# ones = np.ones(10)
# ones

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
vowels = np.array(['a','e','i', 'o','u'])
vowels

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [5]:
ones = np.ones(10, dtype = int).reshape(2, 5)
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
myarray1 = np.array([[2.7, 0, -2],[3.4, 10.6, 0],[-19, 99.9, 13]])
# myarray1 = np.array([[2.7, 0, -2],[3.4, 10.6, 0],[-19, 99.9, 13]]).reshape(3,3)
myarray1

array([[  2.7,   0. ,  -2. ],
       [  3.4,  10.6,   0. ],
       [-19. ,  99.9,  13. ]])

In [7]:
myarray2 = np.arange(4, 4 + 15*4,4, dtype = float).reshape(3,5)
myarray2

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]])

Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [8]:
#Write your answer here

myarray2.ndim, myarray2.size, myarray2.dtype, myarray2.itemsize, myarray2.shape

(2, 15, dtype('float64'), 8, (3, 5))

In [9]:
ones.reshape(1,10)
ones.shape

(2, 5)

In [10]:
q3 = vowels[1:3]

In [11]:
q4 = myarray1[1:3,]

In [12]:
q5 = myarray1[:, 0:2]
q5

array([[  2.7,   0. ],
       [  3.4,  10.6],
       [-19. ,  99.9]])

In [13]:
q6 = myarray1[1:3, 0:1]
q6

array([[  3.4],
       [-19. ]])

In [14]:
# q7 = np.flip(vowels)
q7 = vowels[::-1]
q7

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [15]:
# Write your answer here
q1 = ones/3

In [16]:
q2 = myarray2[:, :3] + myarray1
q2

array([[  6.7,   8. ,  10. ],
       [ 27.4,  38.6,  32. ],
       [ 25. , 147.9,  65. ]])

In [17]:
q3 = myarray2[:, :3] - myarray1
q3

array([[  1.3,   8. ,  14. ],
       [ 20.6,  17.4,  32. ],
       [ 63. , -51.9,  39. ]])

In [18]:
q4 = myarray1 * myarray2[:, :3]
q4

array([[  10.8,    0. ,  -24. ],
       [  81.6,  296.8,    0. ],
       [-836. , 4795.2,  676. ]])

In [19]:
#q5
myarray3 = np.dot(myarray1, myarray2)
myarray3

array([[ -77.2,  -74.4,  -71.6,  -68.8,  -66. ],
       [ 268. ,  324. ,  380. ,  436. ,  492. ],
       [2893.6, 3269.2, 3644.8, 4020.4, 4396. ]])

In [20]:
q6 = myarray1 / myarray2[:, :3]
q6

array([[ 0.675     ,  0.        , -0.16666667],
       [ 0.14166667,  0.37857143,  0.        ],
       [-0.43181818,  2.08125   ,  0.25      ]])

In [21]:
q7 = (myarray1 ** 3)/2
q7

array([[ 9.841500e+00,  0.000000e+00, -4.000000e+00],
       [ 1.965200e+01,  5.955080e+02,  0.000000e+00],
       [-3.429500e+03,  4.985015e+05,  1.098500e+03]])

In [22]:
q8 = np.round(np.sqrt(myarray2)/2,2)
q8

array([[1.  , 1.41, 1.73, 2.  , 2.24],
       [2.45, 2.65, 2.83, 3.  , 3.16],
       [3.32, 3.46, 3.61, 3.74, 3.87]])

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [23]:
# Write your answer here
q1 = myarray2.T
q1
# np.transpose(myarray2)


array([[ 4., 24., 44.],
       [ 8., 28., 48.],
       [12., 32., 52.],
       [16., 36., 56.],
       [20., 40., 60.]])

In [24]:
q2 = vowels[::-1]
q2

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

In [25]:
# 0 by columns and 1 by rows
print(myarray1)
print(np.sort(myarray1))
print(np.sort(myarray1, 0))

[[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
[[ -2.    0.    2.7]
 [  0.    3.4  10.6]
 [-19.   13.   99.9]]
[[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [26]:
# Write your answer here
myarray4 = np.arange(-1, -1+0.25*42, 0.25).reshape(14,3)
np.array_split(myarray4, 3)

[array([[-1.  , -0.75, -0.5 ],
        [-0.25,  0.  ,  0.25],
        [ 0.5 ,  0.75,  1.  ],
        [ 1.25,  1.5 ,  1.75],
        [ 2.  ,  2.25,  2.5 ]]),
 array([[2.75, 3.  , 3.25],
        [3.5 , 3.75, 4.  ],
        [4.25, 4.5 , 4.75],
        [5.  , 5.25, 5.5 ],
        [5.75, 6.  , 6.25]]),
 array([[6.5 , 6.75, 7.  ],
        [7.25, 7.5 , 7.75],
        [8.  , 8.25, 8.5 ],
        [8.75, 9.  , 9.25]])]

Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [27]:
# Write your ansewr here
q1 = np.sum(myarray4)
q1

173.25

In [28]:
myarray4

array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ],
       [ 1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ],
       [ 2.75,  3.  ,  3.25],
       [ 3.5 ,  3.75,  4.  ],
       [ 4.25,  4.5 ,  4.75],
       [ 5.  ,  5.25,  5.5 ],
       [ 5.75,  6.  ,  6.25],
       [ 6.5 ,  6.75,  7.  ],
       [ 7.25,  7.5 ,  7.75],
       [ 8.  ,  8.25,  8.5 ],
       [ 8.75,  9.  ,  9.25]])

In [29]:
q2 = np.sum(myarray4, axis=1)
q2

array([-2.25,  0.  ,  2.25,  4.5 ,  6.75,  9.  , 11.25, 13.5 , 15.75,
       18.  , 20.25, 22.5 , 24.75, 27.  ])

In [30]:
q3 = np.sum(myarray4, axis=0)
q3

array([54.25, 57.75, 61.25])

In [31]:
q4 = np.max(myarray4)
q4

9.25

In [32]:
q5 = np.min(myarray4, axis=1)
q5

array([-1.  , -0.25,  0.5 ,  1.25,  2.  ,  2.75,  3.5 ,  4.25,  5.  ,
        5.75,  6.5 ,  7.25,  8.  ,  8.75])

In [33]:
q6 = np.mean(myarray4, axis=1)
q6

array([-0.75,  0.  ,  0.75,  1.5 ,  2.25,  3.  ,  3.75,  4.5 ,  5.25,
        6.  ,  6.75,  7.5 ,  8.25,  9.  ])

In [34]:
q7 = np.std(myarray4, axis=0)
q7

array([3.02334666, 3.02334666, 3.02334666])

#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [35]:
# Write your answer here
import pandas as pd

capitals = pd.read_csv('country-capital-lat-long-population.csv')
capitals.head()

Country           Capital City  Latitude  Longitude  Population  \
0     Afghanistan                  Kabul   34.5289    69.1725     4011770   
1         Albania        Tiranë (Tirana)   41.3275    19.8189      475577   
2         Algeria  El Djazaïr  (Algiers)   36.7525     3.0420     2693542   
3  American Samoa              Pago Pago  -14.2781  -170.7025       48526   
4         Andorra       Andorra la Vella   42.5078     1.5211       22614   

  Capital Type  
0      Capital  
1      Capital  
2      Capital  
3      Capital  
4      Capital

In [36]:
# Convert the latitude and longitude columns to a NumPy array
coordinates = capitals[['Latitude', 'Longitude']].to_numpy()
coordinates

array([[ 3.452890e+01,  6.917250e+01],
       [ 4.132750e+01,  1.981890e+01],
       [ 3.675250e+01,  3.042000e+00],
       [-1.427810e+01, -1.707025e+02],
       [ 4.250780e+01,  1.521100e+00],
       [-8.836800e+00,  1.323430e+01],
       [ 1.821700e+01, -6.305780e+01],
       [ 1.711720e+01, -6.184570e+01],
       [-3.460510e+01, -5.840040e+01],
       [ 4.018200e+01,  4.451460e+01],
       [ 1.252400e+01, -7.002700e+01],
       [-3.528350e+01,  1.491281e+02],
       [ 4.820640e+01,  1.637070e+01],
       [ 4.037770e+01,  4.989200e+01],
       [ 2.505820e+01, -7.734310e+01],
       [ 2.621540e+01,  5.058320e+01],
       [ 2.371040e+01,  9.040740e+01],
       [ 1.310000e+01, -5.961670e+01],
       [ 5.390000e+01,  2.756670e+01],
       [ 5.084670e+01,  4.349900e+00],
       [ 1.725000e+01, -8.876670e+01],
       [ 6.365400e+00,  2.418300e+00],
       [ 3.229150e+01, -6.477800e+01],
       [ 2.746610e+01,  8.964190e+01],
       [-1.650000e+01, -6.815000e+01],
       [ 4.384860e+01,  1

In [37]:
# Get the coordinates of Riyadh (Saudi Arabia's capital)
riyadh_coords = coordinates[capitals['Country'] == 'Saudi Arabia'][0]
riyadh_coords 

array([24.6905, 46.7096])

In [47]:
# Exclude Riyadh from the coordinates array
other_coords = np.sqrt(np.sum((riyadh_coords - coordinates) ** 2, axis = 1))
other_coords[other_coords == 0] = 9999
closest = np.argmin(other_coords)
capitals.iloc[closest, :]

Country                     Bahrain
Capital City    Al-Manamah (Manama)
Latitude                    26.2154
Longitude                   50.5832
Population                   564631
Capital Type                Capital
Name: 15, dtype: object

#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [48]:
# Write your answer here
# Get the coordinates of Washington DC
dc_coords = coordinates[capitals['Capital City'] == 'Washington, D.C.'][0]
dc_coords

array([ 38.8951, -77.0364])

In [49]:
# Exclude Washington DC from the coordinates array
other_coords2 = coordinates[capitals['Capital City'] != 'Washington, D.C.']
other_coords2

array([[ 3.452890e+01,  6.917250e+01],
       [ 4.132750e+01,  1.981890e+01],
       [ 3.675250e+01,  3.042000e+00],
       [-1.427810e+01, -1.707025e+02],
       [ 4.250780e+01,  1.521100e+00],
       [-8.836800e+00,  1.323430e+01],
       [ 1.821700e+01, -6.305780e+01],
       [ 1.711720e+01, -6.184570e+01],
       [-3.460510e+01, -5.840040e+01],
       [ 4.018200e+01,  4.451460e+01],
       [ 1.252400e+01, -7.002700e+01],
       [-3.528350e+01,  1.491281e+02],
       [ 4.820640e+01,  1.637070e+01],
       [ 4.037770e+01,  4.989200e+01],
       [ 2.505820e+01, -7.734310e+01],
       [ 2.621540e+01,  5.058320e+01],
       [ 2.371040e+01,  9.040740e+01],
       [ 1.310000e+01, -5.961670e+01],
       [ 5.390000e+01,  2.756670e+01],
       [ 5.084670e+01,  4.349900e+00],
       [ 1.725000e+01, -8.876670e+01],
       [ 6.365400e+00,  2.418300e+00],
       [ 3.229150e+01, -6.477800e+01],
       [ 2.746610e+01,  8.964190e+01],
       [-1.650000e+01, -6.815000e+01],
       [ 4.384860e+01,  1

In [50]:
# Calculate the distances
distances2 = np.linalg.norm(other_coords2 - dc_coords, axis=1)
distances2

array([146.27407884,  96.88583853,  80.10705887, 107.70667337,
        78.6405265 , 102.11333682,  24.95966902,  26.5524819 ,
        75.82598431, 121.55781222,  27.28674776, 238.0185828 ,
        93.87005187, 126.93705853,  13.84029864, 128.24795163,
       168.13090517,  31.12608443, 105.67381678,  82.25916709,
        24.6193073 ,  85.85587187,  13.92393276, 167.06967927,
        56.10334401,  95.5213246 , 120.98026568,  61.93975896,
        23.95023621, 194.96403946, 100.43260565,  80.02406987,
       114.49235929,  58.6510713 , 183.99387731,  95.22940894,
         6.65742269,  28.14619001,  20.08261727, 101.63811295,
        95.89834255,  75.63513392,  75.24644036,  72.63346147,
       193.43624935, 191.94560091, 191.31229871, 199.06436224,
        34.41247324, 130.49954689, 101.91060707, 102.26544698,
        29.81151844,  80.34918028,  93.27140676,  16.65555726,
        27.98542988, 110.4664807 ,  92.13957045, 202.7907475 ,
       101.96432854,  91.15972648, 123.24443554,  28.31

In [51]:
# Find the indices of the 10 closest cities
closest_city_indices = np.argpartition(distances2, 10)[:10]
closest_city_indices

array([215,  55,  22,  14,  36,  38,  94, 107,  64, 177], dtype=int64)

In [52]:
# Get the names of the countries and the coordinates
countries = capitals['Country'][closest_city_indices].values
closest_city_coordinates = other_coords2[closest_city_indices]

# Print the results
print("Top 10 closest countries:")
print(countries)
print("\nCoordinates of the top 10 closest cities:")
print(closest_city_coordinates)

Top 10 closest countries:
['Turks and Caicos Islands' 'Cuba' 'Bermuda' 'Bahamas' 'Canada'
 'Cayman Islands' 'Haiti' 'Jamaica' 'Dominican Republic'
 'Saint Pierre and Miquelon']

Coordinates of the top 10 closest cities:
[[ 21.4612 -71.1419]
 [ 23.1195 -82.3785]
 [ 32.2915 -64.778 ]
 [ 25.0582 -77.3431]
 [ 45.4166 -75.698 ]
 [ 19.2866 -81.3744]
 [ 18.5392 -72.335 ]
 [ 17.997  -76.7936]
 [ 18.4896 -69.9018]
 [ 46.7738 -56.1815]]
